name: Deployment CI/CD Pipeline

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main

jobs:
  # Test job: Check Wazuh configurations
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Wazuh container
        run: |
          docker pull wazuh/wazuh:latest

      - name: Run automated tests on Wazuh configurations
        run: |
          docker run --rm -v ${{ github.workspace }}/wazuh_rules:/wazuh_rules wazuh/wazuh:latest \
            /bin/bash -c "run-wazuh-tests.sh"  # Replace with actual test command or script

  # Deploy job: Deploy updated Wazuh rules to the Wazuh container
  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensure deploy only runs if tests pass

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Deploy Wazuh detection rules
        run: |
          docker pull wazuh/wazuh:latest
          docker run --rm -v ${{ github.workspace }}/wazuh_rules:/wazuh_rules wazuh/wazuh:latest \
            /bin/bash -c "cp /wazuh_rules/*.xml /var/ossec/etc/rules/ && /var/ossec/bin/ossec-control restart"
