name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Wazuh Manager Docker image (if needed)
      run: |
        docker build -t wazuh-manager:latest .

    - name: Run Wazuh Manager Docker container
      run: |
        docker run -d --name wazuh-manager -p 1514:1514 -p 1515:1515 -p 514:514/udp -p 55000:55000 wazuh-manager:latest

    - name: Copy custom rules to Wazuh container
      run: |
        docker cp custom-rules.xml wazuh-manager:/var/ossec/etc/rules/custom-rules.xml

    - name: Restart Wazuh Manager service
      run: |
        docker exec wazuh-manager /bin/bash -c "/var/ossec/bin/ossec-control restart"

    - name: Set deployment output
      run: |
        echo "DEPLOYMENT_STATUS=successful" >> $GITHUB_ENV  # Save status to an environment variable

    - name: Run Tests (optional)
      run: |
        # Test step, if you want to validate the changes
        echo "Tests can be added here"
